import csv

input_files = [
    "gc_report.csv",  # default
    "gc_1.2.csv",
    "gc_1.5.csv",
    "gc_1.8.csv",
    "gc_2.0.csv"
]

summary_data = []

for file in input_files:
    with open(file, 'r') as f:
        reader = csv.DictReader(f)
        gc_times = [float(row["GC Time (ms)"]) for row in reader if row["GC Time (ms)"]]

    if file == "gc_report.csv":
        heap_factor = "default"
    else:
        heap_factor = file.replace("gc_", "").replace(".csv", "")

    gc_count = len(gc_times)
    total_time = round(sum(gc_times), 2)
    max_time = round(max(gc_times), 2)

    summary_data.append([heap_factor, gc_count, total_time, max_time])

summary_data.sort(key=lambda x: float(x[0]) if x[0] != 'default' else -1)

with open("summary.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["Generated by script: generate_summary.py (Python)"])  # заголовок-коментар
    writer.writerow(["HEAP_GROWTH_FACTOR", "GC Count", "Total GC Time (ms)", "Max GC Pause (ms)"])
    writer.writerows(summary_data)

print("✅ summary.csv created.")
